<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Tutorial</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-file-systems" class="section level2">
<h2>File Systems</h2>
<p>Follow along with the explanation by typing things as you read.</p>
<p>Your computer stores information in <strong>files</strong> and organizes these files using <strong>directories</strong> (on some systems they are called <strong>folders</strong>). Most of you are familiar with how this structure is represented graphically.</p>
<p>The data structure underlying a file system is that of a <strong>tree</strong> (to keep this discussion simple I am leaving out a few complications with which some of you may be familiar such as links and file streams). The <strong>nodes</strong> in the tree represent directories. We typically think of files as <strong>belonging</strong> to (or being <strong>within</strong>) a directory, and as such, usually don’t represent the files as nodes. An edge represents the location of a subdirectory. For example, if the directory <code>var</code> contained the directory <code>log</code> then that situation would be represented diagrammatically as follows:</p>
<pre><code>(var)
  |
  |
(log)</code></pre>
<p>In the example above we would say that <code>log</code> is a <strong>subdirectory</strong> of <code>var</code>. Every directory has a <strong>parent directory</strong> (more on that below)</p>
<div id="section-special-directories" class="section level3">
<h3>Special Directories</h3>
<p>There is a special node in a tree called the root, and the corresponding directory on your computer is called the <strong>root directory</strong>. The parent of root is also root. This is a property that is unique to root. Parent directories are denoted by <code>..</code> (which means “up one”).</p>
<p>Each user has a special directory associated to their <strong>user account</strong> called their <strong>home directory</strong>.</p>
<p>On Linux machines there are some special sub directories associated to lower-level details of the computer. For example the <code>/dev</code> subdirectory provides a mechanism for accessing Linux <strong>devices</strong>.</p>
<p>There is another directory known as the <strong>working directory</strong>. In a command line situation this is the default location at which things occur. It’s name can be listed using <code>pwd</code> (from the terminal), and using <code>getwd()</code> in an R Console. The parent directory is specified using <code>..</code> and the current working directory is specified using <code>.</code>.</p>
</div>
<div id="section-paths" class="section level3">
<h3>Paths</h3>
<p>The location of a file is specified by a</p>
<ul>
<li>file name, and a</li>
<li>file path</li>
</ul>
<p>Generally speaking there are two major ways to specify the path to a desired file:</p>
<ul>
<li>Absolute and</li>
<li>Relative</li>
</ul>
<p>An absolute path is provided relative to the root node. For example, here is the absolute path to the working directory used by the RMarkdown knitting process:</p>
<pre><code>## /home/dolanp/dsci3701/NetworkingAndFileSystems</code></pre>
<p>In all cases there is a special character used to separate the directory names. In unix (and thus linux and Macintosh) the separator character is <code>/</code>. In windows the character is <code>\</code>. Since <code>\</code> is used as an <strong>escape character</strong> in most programming languages (for example <code>\n</code> represents a newline character), it can be tedious to represent a Windows file path as a string. Every <code>\</code> in the path has to be replaced by <code>\\</code> in the string (because <code>\\</code> is how a single back-slash character is represented)</p>
<p>Most languages dealing with files will use <code>/</code> even on systems that use <code>\</code> so we will use <code>/</code> as our path separator character.</p>
<p>Root is specified as <code>/</code>, so the directions describe how to traverse the file structure tree from the root, <code>/</code> to the desired node (which represents a subdirectory).</p>
<p>On the other hand <strong>relative paths</strong> are given from the current working directory. So consider the following subset of a file system (where the working directory is specified with an asterisk ’*’)</p>
<pre><code>                (home)
                /    \
            (*peter) (washington)</code></pre>
<p>Suppose that the <code>washington</code> directory contained a file named <code>resource.txt</code>. The relative path from the current working directory to that resource would be <code>../washington/resource.txt</code>. Notice the use of <code>..</code> to represent the “parent directory” (which is <code>home</code> in this case).</p>
<p>The symbol <code>~</code> represents the current users home directory and <code>~&lt;username&gt;</code> represents another users home directory, for example <code>~washington</code> would be the home directory for washington.</p>
</div>
<div id="section-search-path" class="section level3">
<h3>Search Path</h3>
<p>Programs are run from the command line by specifying the file name. The absolute path for a command will always work but may be a hassle to type. The <strong>search path</strong> is a list of directories that are <strong>searched</strong> for a command. For example the <code>ls</code> command is actually <code>/bin/ls</code>. Because the subdirectory <code>/bin</code> is in the search path, I can type <code>ls</code> in the command line and no matter what directory I am in I will see the contents of the directory. The <code>whereis</code> command will show the directories in the search path that contain a command (this is helpful if more than one version of a program is iinstalled)</p>
</div>
<div id="section-quiz" class="section level3">
<h3>Quiz</h3>
<p>Answer the following questions for the following directory structure:</p>
<pre><code>                       (/)
       _________________|___________________
      |           |               |         |
    (bin)       (var)           (home)     (tmp)
                  |            /     \
                (log)     (*Peter)   (washington)
                              |
                          (project)</code></pre>
<div class="panel panel-default">
<div class="panel-heading tutorial-panel-heading">Quiz</div>
<table class="table quiz-table">
<tr>
<td>

<div id="htmlwidget-28a263fb077c90ac8647" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-28a263fb077c90ac8647">{"x":{"question":"Which path is the absolute path specifying the file <code>vim.log<\/code> in the <code>log<\/code> subdirectory","answers":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"label":"quiz-1","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Which path is the absolute path specifying the file <code>vim.log<\/code> in the <code>log<\/code> subdirectory","a":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-a3d0414782b81c74cf75" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-a3d0414782b81c74cf75">{"x":{"question":"Which path is the relative path specifying the file <code>vim.log<\/code> in the <code>log<\/code> subdirectory","answers":[{"option":"/var/log/vim.log","correct":false,"message":null},{"option":"../../var/log/vim.log","correct":true,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"label":"quiz-2","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Which path is the relative path specifying the file <code>vim.log<\/code> in the <code>log<\/code> subdirectory","a":[{"option":"/var/log/vim.log","correct":false,"message":null},{"option":"../../var/log/vim.log","correct":true,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-f30151c0bba1bba85641" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-f30151c0bba1bba85641">{"x":{"question":"Which path is the path specifying the file <code>vim.log<\/code> from the user <code>washington<\/code>&#39;s home directory","answers":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"label":"quiz-3","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Which path is the path specifying the file <code>vim.log<\/code> from the user <code>washington<\/code>&#39;s home directory","a":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-32b7190f7010d60c50c3" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-32b7190f7010d60c50c3">{"x":{"question":"Which linux command shows the current working directory","answers":[{"option":"<code>pwd<\/code>","correct":true,"message":null},{"option":"<code>ls<\/code>","correct":false,"message":null},{"option":"<code>cd<\/code>","correct":false,"message":null},{"option":"<code>cat<\/code>","correct":false,"message":null}],"label":"quiz-4","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Which linux command shows the current working directory","a":[{"option":"<code>pwd<\/code>","correct":true,"message":null},{"option":"<code>ls<\/code>","correct":false,"message":null},{"option":"<code>cd<\/code>","correct":false,"message":null},{"option":"<code>cat<\/code>","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-03a8c9f056e5529a9db4" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-03a8c9f056e5529a9db4">{"x":{"question":"Multiple copies of the linux command <code>myCMD<\/code> exist in the subdirectories <code>/usr/bin<\/code>, <code>/usr/etc<\/code>, and in <code>/usr/sbin<\/code>.  The search path is <code>/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin<\/code>.  What is the full path of the command that will be run if a user types <code>myCMD<\/code> at the terminal window?","answers":[{"option":"/usr/bin","correct":false,"message":null},{"option":"/usr/sbin","correct":true,"message":null},{"option":"/root/anaconda3/bin","correct":false,"message":null},{"option":"/usr/etc","correct":false,"message":null}],"label":"quiz-5","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Multiple copies of the linux command <code>myCMD<\/code> exist in the subdirectories <code>/usr/bin<\/code>, <code>/usr/etc<\/code>, and in <code>/usr/sbin<\/code>.  The search path is <code>/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin<\/code>.  What is the full path of the command that will be run if a user types <code>myCMD<\/code> at the terminal window?","a":[{"option":"/usr/bin","correct":false,"message":null},{"option":"/usr/sbin","correct":true,"message":null},{"option":"/root/anaconda3/bin","correct":false,"message":null},{"option":"/usr/etc","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
</table>
</div>
</div>
</div>
<div id="section-navigating-the-file-system" class="section level2">
<h2>Navigating the File System</h2>
<p>Open RStudio and look at your <code>Files</code> tab (mine is in the lower right corner). You will probably see your <strong>home directory</strong>. Here you navigate using the mouse. You can see the <code>..</code> specification for the parent directory, and you can enter a subdirectory by clicking on the appropriate folder. Notice that this does NOT change the working directory in the console, but the “More” droplist allows you to “Set as Working Directory”. It also allows you to “Change to Working Directory”.</p>
<p>In the terminal window you no longer have the ability to click. Instead you use the command <code>cd</code> for <strong>change directory</strong>. The <code>cd</code> command accepts a path as an argument. That path can be relative or absolute. It is common to use <code>cd ..</code> to move up to the parent directory.</p>
<p>You can list the contents of the directory with <code>ls</code>. The command <code>ls -l</code> is list with the <strong>long flag</strong> and that will show you more information.</p>
<p>Open a terminal window in JupyterHub change directory to the <em>parent directory of your home directory</em> and do the command <code>ls -l</code></p>
<p>You will see all the home directories of the other users. Each row is a separate file or directory. Each column reveals different information. :</p>
<table>
<colgroup>
<col width="25%" />
<col width="35%" />
<col width="38%" />
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Short Name</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Permissions</td>
<td>Specifies whether an entry is file or a directory and the <strong>permissions</strong> (see next section)</td>
</tr>
<tr class="even">
<td>2</td>
<td>Hard links</td>
<td>Specifies how many “links” are associated to the entry. Normal files typically have 1 (we aren’t discussing linux hard links here), directories typically have as many as the number of subdirectories they contain (NOTE: Every subdirectory contains an entry for <code>.</code> and for <code>..</code> so for a directory this number is at least 2)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Owner</td>
<td>The user that “owns” the entry (see below)</td>
</tr>
<tr class="even">
<td>4</td>
<td>Group</td>
<td>The group to which the entry belongs (see below)</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Size</td>
<td>The size of the entry (even directories take up disk space so they have a size too)</td>
</tr>
<tr class="even">
<td>6</td>
<td>Date</td>
<td>(you might count these are 6,7, and 8: month, day, time (or year)).</td>
</tr>
<tr class="odd">
<td>7</td>
<td>name</td>
<td>This is the name of the file or directory</td>
</tr>
</tbody>
</table>
<div id="section-hidden-files" class="section level3">
<h3>Hidden files</h3>
<p>File starting with a period are hidden. You need to use <code>-a</code> to see them. So <code>ls -al</code> will list all the files, including the hidden ones in long form.</p>
</div>
<div id="section-changing-directories" class="section level3">
<h3>Changing Directories</h3>
<p>The <code>cd</code> command is used to change the working directory. It accepts both relative and absolute file paths. Not all possible paths are allowed (see the <em>Permissions</em> section for more details).</p>
<p>For example to change the working directory to the parent of the current one use <code>cd ..</code>. Similarly, one can change to one’s home directory using <code>cd ~</code>.</p>
</div>
</div>
<div id="section-permissions" class="section level2">
<h2>Permissions</h2>
<p>The first column in the long list of the files in the <code>/home</code> directory specifies the <strong>permissions</strong>. There are three categories of <strong>permission scope</strong> and three categories of <strong>permission types</strong> used in plain linux. There is a much more sophisticated permission system known as selinux (security enhanced linux), but we are not going to cover that in this class.</p>
<p>Every entry (which I will also call a <strong>resource</strong>) in a directory has both an</p>
<ul>
<li><strong>owner</strong> and a</li>
<li><strong>group</strong></li>
</ul>
<p>The owner is a user account (secretly it’s just a number). User accounts in linux can belong to <strong>groups</strong>. A user can belong to multiple groups. However a directory entry can only be associated to one group.</p>
<p>The three permission scopes are related to these concepts:</p>
<ul>
<li>User (symbolized as <code>u</code>). This is the <strong>owner</strong> of the resource</li>
<li>Group (symbolized as <code>g</code>). This applies to any account that is in the same group as the resource</li>
<li>Other (symbolized as <code>o</code>). This applies to every other account</li>
</ul>
<p>The permission column is exactly 10 characters long. The first letter in the permission column is usually either <code>d</code> or <code>-</code>. Which indicates whether or not the entry is a directory or a file. The remaining 9 are broken into groups of three. The first group is for the user <code>u</code>. The second triplet is fo the group <code>g</code>, and the third triplet is for the other accounts <code>o</code>.</p>
<p>Within each triplet there the three characters correspond to</p>
<ul>
<li>READ (this will usually be <code>r</code> or <code>-</code>)</li>
<li>WRITE (this will usually be <code>w</code> or <code>-</code>)</li>
<li>EXECUTE (this will usually be <code>x</code> or <code>-</code>)</li>
</ul>
<p>So, for example</p>
<p>The permission string: <code>-rw-r--r--</code> can be understand as the following 4 components:</p>
<pre><code>-   |  rw-  | r--   | r--
type|  user | group | other</code></pre>
<p>So it is a normal file. The user (owner) has read and write access to the file. Group members have read access and so do all other accounts.</p>
<p><code>r</code> means <strong>read</strong> access. The contents of the resource can be examined. For a file this means the contents can of the file can be read (perhaps with a command such as <code>cat</code>, or <code>less</code>). For a directory this means that the entries in the directory can be listed (perhaps with <code>ls</code>)</p>
<p><code>w</code> means <strong>write</strong>. A file can be over-written even if it can’t be read so <code>-w-</code> is a possible triplet. For a directory, <code>w</code> means that files can be added or removed. Without <code>w</code> on a directory files can’t be added or removed.</p>
<p><code>x</code> means <strong>executable</strong>. For files, this means that the file either a <strong>binary executable</strong> or a <strong>shell script</strong> can be run from the command line. For directories this means that the subdirectory with the <code>x</code> permission can be part of a file path. This allows one user to provide resources to another user without exposing the upper level contents of their system. Without <code>x</code> most details become invisible. If I have <code>r</code> access I can still see file names… but no information about them. I can <strong>not</strong> change to that directory if I don’t have <code>x</code>. I <strong>can</strong> even without <code>r</code> (although I can’t see anything).</p>
<p>There are other complications (such as the “sticky bit” and the “super user” bit which I’m leaving out)</p>
<div id="section-changing-permissions" class="section level3">
<h3>Changing Permissions</h3>
<p>You can change permissions using the <code>chmod</code> command. The basic structures is <code>chmod [ugo][+/-][rwx] &lt;file&gt;</code></p>
<p>So, for example, to add the ability for the owner of the file to execute the script <code>hello.sh</code> (in the current working directory). I could type <code>chmod u+x hello.sh</code>.</p>
<p>I can change owner with <code>chown &lt;user&gt; &lt;file&gt;</code> (if I own it). I can also change the group using <code>chown :&lt;group&gt; &lt;file&gt;</code>. Or change the owner and the group simultaneously: <code>chown &lt;user&gt;:&lt;group&gt; &lt;file&gt;</code>.</p>
<div class="panel panel-default">
<div class="panel-heading tutorial-panel-heading">Quiz</div>
<table class="table quiz-table">
<tr>
<td>

<div id="htmlwidget-bcb25abc136498b7a882" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-bcb25abc136498b7a882">{"x":{"question":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>user<\/strong> (aka the owner)","answers":[{"option":"read","correct":true,"message":null},{"option":"write","correct":true,"message":null},{"option":"execute","correct":false,"message":null},{"option":"group access","correct":false,"message":null}],"label":"pquiz-1","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>user<\/strong> (aka the owner)","a":[{"option":"read","correct":true,"message":null},{"option":"write","correct":true,"message":null},{"option":"execute","correct":false,"message":null},{"option":"group access","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-224f118517d8b76d3cb9" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-224f118517d8b76d3cb9">{"x":{"question":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>other users<\/strong>","answers":[{"option":"read","correct":true,"message":null},{"option":"write","correct":false,"message":null},{"option":"execute","correct":false,"message":null},{"option":"group access","correct":false,"message":null}],"label":"pquiz-2","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>other users<\/strong>","a":[{"option":"read","correct":true,"message":null},{"option":"write","correct":false,"message":null},{"option":"execute","correct":false,"message":null},{"option":"group access","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-a8fb124ed2282414328d" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-a8fb124ed2282414328d">{"x":{"question":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>group<\/strong> (aka the owner)","answers":[{"option":"read","correct":false,"message":null},{"option":"write","correct":true,"message":null},{"option":"execute","correct":true,"message":null},{"option":"group access","correct":false,"message":null}],"label":"pquiz-3","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"The permissions column for an <code>ls -l<\/code> entry is drw--wxr--.  What priviliges are granted to the <strong>group<\/strong> (aka the owner)","a":[{"option":"read","correct":false,"message":null},{"option":"write","correct":true,"message":null},{"option":"execute","correct":true,"message":null},{"option":"group access","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-7a2e945e9dba354c5f55" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-7a2e945e9dba354c5f55">{"x":{"question":"In order to list the entries in a directory what permission(s) must be ","answers":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"label":"pquiz-4","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"In order to list the entries in a directory what permission(s) must be ","a":[{"option":"/var/log/vim.log","correct":true,"message":null},{"option":"../../var/log/vim.log","correct":false,"message":null},{"option":"~washington/../../var/log/vim.log","correct":false,"message":null},{"option":"../var/log/vim.log","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
<tr>
<td>

<div id="htmlwidget-8c3003aa9bad59dcf719" style="width:100%;height:auto;", class = "quiz html-widget">
<div class="panel panel-default">
<div class="panel-body quizArea">
</div>
</div>
</div>

<script type="application/json" data-for="htmlwidget-8c3003aa9bad59dcf719">{"x":{"question":"Which linux command shows the current working directory","answers":[{"option":"<code>pwd<\/code>","correct":true,"message":null},{"option":"<code>ls<\/code>","correct":false,"message":null},{"option":"<code>cd<\/code>","correct":false,"message":null},{"option":"<code>cat<\/code>","correct":false,"message":null}],"label":"pquiz-5","skipStartButton":true,"perQuestionResponseAnswers":true,"perQuestionResponseMessaging":true,"preventUnanswered":true,"displayQuestionCount":false,"displayQuestionNumber":false,"disableRanking":true,"nextQuestionText":"","checkAnswerText":"Submit Answer","allowRetry":false,"randomSortAnswers":false,"json":{"info":{"name":"","main":""},"questions":[{"q":"Which linux command shows the current working directory","a":[{"option":"<code>pwd<\/code>","correct":true,"message":null},{"option":"<code>ls<\/code>","correct":false,"message":null},{"option":"<code>cd<\/code>","correct":false,"message":null},{"option":"<code>cat<\/code>","correct":false,"message":null}],"correct":"Correct!","incorrect":"Incorrect."}]}},"evals":[],"jsHooks":[]}</script>
</td>
</tr>
</table>
</div>
</div>
</div>
<div id="section-network-topology" class="section level2">
<h2>Network Topology</h2>
<p>If a file system’s structure can be described by a tree then a network’s structure can be described by a graph (in the node and edge meaning of the term).</p>
<p>Every network entity under consideration is associated to a node, and the edges between nodes represent a channel of communication.</p>
<p>Most home networks have a <strong>star topology</strong> where one central hub mediates communication between all other network capable devices in the house. Businesses might have a more complicated topology where different departments have distinct networks to help keep corporate interests separated.</p>
<p>Most networked computers have multiple <strong>interfaces</strong> that are the means by which the computer and its programs interacts with the larger network. For example, the JupyterHub server has two: One is an ethernet interface (more on that below) that is the means by which the computer communicates with the larger network, and the other is a special <strong>loop back</strong> interface that allows a program (or user) a special way to refer to the machine itself.</p>
<p>All modern networking divides the communication process into <strong>layers</strong>. The most popular formal networking model recognizes seven layers. The internet, as it is usually used, is designed around four (explained in detail below):</p>
<ul>
<li>link</li>
<li>internet (some references call this the network layer)</li>
<li>transport</li>
<li>application</li>
</ul>
<div id="section-the-link-layer" class="section level3">
<h3>The Link Layer</h3>
<p>In order for information to be transferred it must be broken up into pieces and sent from node to node. The level at which this occurs is the <strong>link layer</strong>. This is the “brass tacks level” where the physical media such as wires or radio waves exist and the level at which the physical conventions used to encode the logical bits and bytes is employed.</p>
<p>Ethernet, whether used by physical cabling like cat6 or wireless connections, is an example of a <strong>link level protocol</strong>. Open up a terminal on a jupyterhub and type <code>ip link</code>. You should see something very similar to the following:</p>
<pre><code>jupyter-test@jupyterhub:~$ ip link
1: lo: &lt;LOOPBACK,UP,LOWER_UP&gt; mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:66:98:30 brd ff:ff:ff:ff:ff:ff</code></pre>
<p>This shows us the two interfaces <code>lo</code> and <code>en3</code>. The first is the loopback interface, and the second is the ethernet interface. The words between the angle brackets <code>&lt;</code> and <code>&gt;</code> are state flags (consider them an answer to a yes/no question). You will, mostly, be ignoring that information, but if you find an important network communication is failing you might want to check for <code>UP</code> and <code>DOWN</code> flags (which should be self-explanatory). The other details you can also usually ignore, but you might be interested in the <code>link/ether</code> address. In our example above that is <code>52:54:00:66:98:30</code>. This is also known as a MAC address and every network device is supposed to have a unique address. Each number separated by <code>:</code> encodes an 8 bit number (aka a <strong>byte</strong>), but, as is usual for telecommunications it is referred to as an <strong>octet</strong>. An octet is usually represented by two hexademical digits, each of which is referred to as a <strong>nibble</strong> (because two nibbles make a byte… ha!).</p>
<p>Recall the following translation pattern:</p>
<pre><code>Hex   |  bytes | |Hex    | bytes | |  hex | bytes | | hex  | bytes
------|--------|-|-------|-------|-|------|-------|-|------|------
0     | 0000   | | 4     | 0100  | | 8    | 1000  | | C    | 1100  
1     | 0001   | | 5     | 0101  | | 9    | 1001  | | D    | 1101
2     | 0010   | | 6     | 0110  | | A    | 1000  | | E    | 1110  
3     | 0011   | | 7     | 0111  | | A    | 1001  | | E    | 1111  </code></pre>
<p>The first 3 octets in a MAC address are the OUI (Organizationally Unique ID). Which indicates the manufacturor of the network device in a publically registered OUI and indicates an in-house identity if the address is privately managed.</p>
<p>In our case those 3 octets are <code>52:54:00</code>. The second nibble of the first octet (in our case <code>2</code>) determines whether or not the address is a <strong>Private mac addresss</strong>. The short answer to whether or not the address is public or private is if the second-to-last bit in the last nibble is a 1 (private) or a 0 (public).</p>
<p>There is a complication involving unicast vs multicast which I’m not going to go into here… so the short version is– if the second number in the first octet is a 2, 6, A, or E, then the address is privately maintained. As can be seen from our first octet of <code>52</code> the MAC address is priately maintained (this usually means it is part of a <strong>virtual</strong> bridge or virtual switch– something managed in software that emulates an actual physical device). That’s the case for us.</p>
</div>
<div id="section-the-internet-layer" class="section level3">
<h3>The internet layer</h3>
<p>This is the layer that has to concern itself with how information passes through (potentially) MULTIPLE nodes to get to its destinaton. This is where the <strong>internet address</strong> comes into play.</p>
<p>In a terminal you can access information at this level using <code>ip address</code>. Try this in a JupyterHub Terminal window. THis is what you’ll see on my server:</p>
<pre><code>jupyter-test@jupyterhub:~$ ip address
1: lo: &lt;LOOPBACK,UP,LOWER_UP&gt; mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:66:98:30 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.224/24 brd 192.168.122.255 scope global dynamic noprefixroute ens3
       valid_lft 2467sec preferred_lft 2467sec
    inet6 fe80::89ff:839d:d7bc:b01a/64 scope link noprefixroute
       valid_lft forever preferred_lft forever</code></pre>
<p>Notice we see both the link level AND new information.</p>
<p>The original (and still most widely used) protocol on the internet is IP v 4 (Internet Protocol version 4). Address are 4 octets– usually represented in decimal rather than hexadecimal. Hence values can range from 0 to 255 (recall that <span class="math inline">\(2^8=256\)</span>).</p>
<p>Our ethernet interface has an ipv4 address of <code>192.168.122.224</code>. The <code>192.168.x.x</code> address block is <strong>private ip</strong> which means that it’s not mean to be used outside of the local network. Some network device will, typically, keep track of a translation table and convert <strong>internal IP</strong> to <strong>external IP</strong>.</p>
<p>The details aren’t particularly important for this class, but you should be able to look at a ver 4 ip address and know if it is public or private. THere are 3 <strong>blocks</strong> of private ip addresses:</p>
<ul>
<li>192.168.x.x - (about 65,000 IP addresses)</li>
<li>172.16.0.0 - 172.31.255.255 (about a million IP addresses)</li>
<li>10.x.x.x (around 16.8 million IP addresses)</li>
</ul>
<p>The newer version of the internet is <code>ipv6</code>. (We skipped over version 5). It is not as widely adopted, but most network devices can recognize it now. An ipv4 address is usually represented with 4 octets (hence 4*8=32 bits). An ipv6 address is 128 bits organized into eight <code>quibbles</code> (short for quad nibbles). Each quibble is 4 hex digits (so 16 bits). The quibbles are separated by colons and an address is allowed to have <strong>one</strong> (and only one) double colon ’::<code>which means all the &quot;left-out&quot; quibbles are 0000.   The reported ipv6 address for</code>en3<code>is</code>fe80::89ff:839d:d7bc:b01a<code>.  Which is short for</code>fe80:0000:0000:0000:89ff::839d:d7bc:b01a`.</p>
<p>Similarly to ipv4 there is a range of ipv6 addresses set aside for something <em>similar</em> to private IP. The difference between ipv4 and ipv6 (in this regard) is that ipv6 wants <strong>all</strong> ip addresses to be unique… in ipv4 the same private ip addresses may appear in many local networks (for example, the URL: <a href="http://192.168.1.1" class="uri">http://192.168.1.1</a> will, for many home networks, allow a user to access the router’s web interface from a web browser run on a client hooked up to the local network). In ipv6 the <code>fe80::</code> address block is set for <strong>auto configuration</strong> however there are so many other octets left over for addresses that even the local addresses can all be unique.</p>
<p>The loopback ipv4 address is always <code>127.0.0.1</code> and for ipv6 it is <code>::1</code>.</p>
</div>
<div id="section-cidr-notation" class="section level3">
<h3>CIDR notation</h3>
<p>You might notice that both the ipv4 and the ipv6 addresses are followed by a single forward slash <code>/</code> and then a number. This is related to <strong>routing</strong>. The way in which information is transferred (via the link level) from one node to another is called routing.</p>
<p>A good analogy for how information is passed from node to node is the process that a letter (in the US) follows as it moves through the mail system:</p>
<ul>
<li>I write a letter and put it in an envelope with an address</li>
<li>I put the sealed letter in my mailbox and raise a flag on the box.</li>
<li>The mail person sees the raised flag, picks up the letter, and delivers the letter to my local postoffice</li>
<li>The post office looks at the address and decides which van needs to take it to the next processing center</li>
<li>The letter is moved from processing center to processing center. At each step the center looks at the letter and decides the next destination.</li>
<li>The letter eventually makes it to the local post office in the destination town</li>
<li>The mail person delivers the letter to the indicated address</li>
<li>The recipient brings the letter inside</li>
<li>The envelope is opened and the letter is read</li>
</ul>
<p>This is, essentially, how the information is delivered between nodes on the internet. The address on the letter allows the information to be transferred to the destination, and the return address allows more correspondance to be sent back to the original person. The destination address on the letter has <strong>hierarchical</strong> directions. For example, my address is</p>
<pre><code>407 East 6th Street
Morris, MN 56267</code></pre>
<p>The first line is my <strong>local address</strong>. The second line indicates the proper town and state. It is more of a general address.</p>
<p>In a CIDR address the number indicates how many bits in the address are associated to the <strong>network</strong> and how many to the <strong>client</strong>. This is similar to saying how many of the 128 bits are used to indicate the first line (<code>407 East 6th street</code>) and how many are used to indicate the second line <code>Morris, MN 56267</code>.</p>
<p>Instead of a postal address the IP address is used. The number after the slash <code>/</code> in the CIDR notation indicates how many bits in the address are related</p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/cerulean.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css","rstudio-theme.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["localforage"]},{"type":"character","attributes":{},"value":["1.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/localforage"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["localforage.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets"]},{"type":"character","attributes":{},"value":["1.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["www"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["htmlwidgets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["htmlwidgets"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["quiz-binding"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["quiz.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/bootstrap.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["localforage"]},{"type":"character","attributes":{},"value":["1.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/localforage"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["localforage.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["slickquiz"]},{"type":"character","attributes":{},"value":["1.5.20"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets/lib/slickquiz"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/slickQuiz.js"]},{"type":"character","attributes":{},"value":["css/slickQuiz.css","css/slickQuizTutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets"]},{"type":"character","attributes":{},"value":["1.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["www"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["htmlwidgets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["htmlwidgets"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["quiz-binding"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["quiz.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/bootstrap.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.15"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["localforage"]},{"type":"character","attributes":{},"value":["1.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/localforage"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["localforage.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.9.2.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["slickquiz"]},{"type":"character","attributes":{},"value":["1.5.20"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["htmlwidgets/lib/slickquiz"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/slickQuiz.js"]},{"type":"character","attributes":{},"value":["css/slickQuiz.css","css/slickQuizTutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.9.2.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34]}},"value":[{"type":"character","attributes":{},"value":["backports","base","compiler","datasets","digest","evaluate","graphics","grDevices","htmltools","htmlwidgets","httpuv","jsonlite","knitr","later","learnr","magrittr","markdown","methods","mime","promises","R6","Rcpp","rmarkdown","rprojroot","shiny","stats","stringi","stringr","tools","utils","withr","xfun","xtable","yaml"]},{"type":"character","attributes":{},"value":["1.1.4","3.5.3","3.5.3","3.5.3","0.6.20","0.14","3.5.3","3.5.3","0.3.6","1.3","1.5.1","1.6","1.24","0.8.0","0.9.2.1","1.5","1.1","3.5.3","0.7","1.0.1","2.4.0","1.0.2","1.15","1.3-2","1.3.2","3.5.3","1.4.3","1.4.0","3.5.3","3.5.3","2.1.2","0.9","1.8-4","2.2.0"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Tutorial</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>

</html>
